name: Scrape latest data

on:
  push:
  workflow_dispatch:
  # schedule:
  #  - cron:  "6 6 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v2
    - name: My first action
      env:
        GITHUB_TOKEN: ${{ secrets.LEV_TOKEN }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install requests
      run: |
          pip install requests pandas regex
    - name: Fetch latest data
      run: |-
        cd lev
        python lev_prices.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
